name: Deploying dev

on:
#   push:
#     branches:
#       - development

jobs:
  test:
    name: Testing
    uses: FaisalBudiono/laravel-boilerplate/.github/workflows/code-test.yml@development

  build:
    name: Build and Push
    environment: development
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Preset Image Name
        run: echo "IMAGE_URL=$(echo ${{ secrets.DOCKER_REGISTRY_NAME }}/${{ vars.IMAGE_NAME }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_NAME }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_URL }}
      - name: Deploy API to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.DEV_APP_NAME }}"
          token: "${{ secrets.DEV_APP_TOKEN }}"
          image: ${{ env.IMAGE_URL }}
      - name: Deploy Worker to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.DEV_APP_WORKER_NAME }}"
          token: "${{ secrets.DEV_APP_WORKER_TOKEN }}"
          image: ${{ env.IMAGE_URL }}
